### ISSUE TITLE
Unknown InResponseTo

### ISSUE THREAD

**Issue by jbrenna** [lightSAML/lightSAML#96] opened 2017-09-26 19:09 UTC
I get random critical errors like this in Symfony when users try to log in with Okta.
```
Uncaught PHP Exception LightSaml\Error\LightSamlContextException: "Unknown InResponseTo '_7ab8386ad4fcf931733b87639a2bb45a5505a0e9af'" at /services/applications/red-secure/vendor/lightsaml/lightsaml/src/LightSaml/Action/Profile/Inbound/StatusResponse/InResponseToValidatorAction.php line 55
```
Bug or something I can fix?

**Comment by glanes** [comment] 2017-10-10 22:49
I am having the same problem, have you found the solution? 
The response is related with the ID when you send a AuthRequest, so when you get the SAMLResponse the same ID return as reference. I checked the table id_entry and the id is there, so don't know what I am missing.

**Comment by tigrang** [comment] 2017-10-18 06:07
@jbrenna @glanes Check the expiry time, maybe system clock is out of sync?

**Comment by jbrenna** [comment] 2017-12-20 09:16
I believe this is the case:
The user types in the url and browser suggest `https://example.com/saml/login_check`.
When user go directly to `login_check`, LightSaml will throw a 500 error.

**Comment by jbrenna** [comment] 2017-12-22 08:40
The 500 error only happens if the user is already logged in.

**Comment by gleydsonsilva** [comment] 2018-04-17 14:23
+1

**Comment by lpalliyaguru** [comment] 2018-08-16 08:55
i am still getting this error. Anyone found a solution ?

**Comment by jbrenna** [comment] 2018-08-16 12:42
Still a problem for me as well. It happens randomly.

**Comment by rsilveira65** [comment] 2018-12-12 13:44
my app is throwing this error, someone fixed it?

**Comment by ragulara93** [comment] 2019-03-14 16:43
Hello,
I have the same issue and that happends randomly.
Anyone has a solution for that please? Or can give me a hint to help me understand why i have this error?
Thank you

**Comment by rvdbogerd** [comment] 2019-05-15 16:12
I just discovered what this error means, and thought I'd share it for future generations :)

One of my clients is working on an old Citrix environment, with very strict security settings/policies. This results in the authorization request being blocked, and then the customer is redirected, then lightsaml is checking in the persistent requestStore IF the request is known by us, which obviously isn't the case. Hope this helps anyone stumbling upon this error in the logs. Cheers!

**Comment by brunoalvarelho** [comment] 2019-10-04 08:20
Uncaught PHP Exception LightSaml\Error\LightSamlContextException: "Unknown InResponseTo ''_30a814f731c10b4153ccfdceab51418e120f99009d" at /services/applications/red-secure/vendor/lightsaml/lightsaml/src/LightSaml/Action/Profile/Inbound/StatusResponse/InResponseToValidatorAction.php line 55

Anyone solve a problem ??

**Comment by djonatanb** [comment] 2019-11-11 20:02
We have figured out what this problem means.
When your client accesses your login URL and gets redirected to the IDP a RequestID is generated and sent. 
When the IDP resolves the logging process and will return to your login_check URL it adds the InResponseTo as part of the request. The thing is that: 1 - InResponseTo is not a mandatory part of the SAML protocol, 2 - if the bundle sees the InResponseTo it tries to MATCH it.
The matching is done through the **RequestStore**. 

So in the same way that you implement (by following the tutorial SpBundle+symfony bridge) your own id_entry IdStore, you will have to implement a persistent RequestStore with it's set, get and remove.
The workflow will call your implementation when it first sets the id, then verify when it receives the request with the "InResponseTo" and if it matches, it will call for the removal. 
The logic behind the Request store is that it will make sure you only receive requests originating from your own system (/login -> setID -> IDP login verification -> /login_check + InResponseTo) and also, that you don't receive a duplicated request (by removing the ID from your persistent resource ).

If it still doesn't make sense let me know and I can share the code.
Take a look here: [https://gist.github.com/djonatanb/194118e5b15727331b8b6279d84e29fe](https://gist.github.com/djonatanb/194118e5b15727331b8b6279d84e29fe) (fixed the link)

**Comment by glanes** [comment] 2020-03-26 03:37
> We have figured out what this problem means.
> When your client accesses your login URL and gets redirected to the IDP a RequestID is generated and sent.
> When the IDP resolves the logging process and will return to your login_check URL it adds the InResponseTo as part of the request. The thing is that: 1 - InResponseTo is not a mandatory part of the SAML protocol, 2 - if the bundle sees the InResponseTo it tries to MATCH it.
> The matching is done through the **RequestStore**.
> 
> So in the same way that you implement (by following the tutorial SpBundle+symfony bridge) your own id_entry IdStore, you will have to implement a persistent RequestStore with it's set, get and remove.
> The workflow will call your implementation when it first sets the id, then verify when it receives the request with the "InResponseTo" and if it matches, it will call for the removal.
> The logic behind the Request store is that it will make sure you only receive requests originating from your own system (/login -> setID -> IDP login verification -> /login_check + InResponseTo) and also, that you don't receive a duplicated request (by removing the ID from your persistent resource ).
> 
> If it still doesn't make sense let me know and I can share the code.
> Take a look here: [https://gist.github.com/djonatanb/194118e5b15727331b8b6279d84e29fe](url)

Hi @djonatanb I thought I had fixed the problem but It is still happening for me, would be possible to share your code so I can try to replicate what you did.
Thanks

**Comment by NullIsNot0** [comment] 2020-10-25 13:10
Has anyone solved it? How do I create _RequestStore_ in Symfony 4.4.15?

**Comment by tmilos** [comment] 2020-10-27 17:52
@NullIsNot0  have you tried with https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Store/Request/RequestStateSessionStore.php?

**Comment by NullIsNot0** [comment] 2020-10-28 15:00
@tmilos thanks for suggestion. I have implemented _RequestStore_ by extending LightSaml\Store\Request\RequestStateStoreInterface and saving data into separate database table. Almost identical to _IdStore_. Everything works fine for me now.
Maybe it would be good to update Getting started guide with steps how to create RequestStore: https://www.lightsaml.com/SP-Bundle/Getting-started/
Another missing piece of information in Getting Started guide was _Logout_ feature. Had to use https://github.com/lightSAML/lightSAML-logout bundle and figure out how to implement it in Symfony. Theese 4 days were really crazy for me.

**Comment by rvdbogerd** [comment] 2020-10-28 21:49
@NullIsNot0 please do. you have very recent knowledge and can add code examples for your fellow peers. Please open a pull request with some added documentation about these two features.

**Comment by NullIsNot0** [comment] 2020-10-28 21:56
Looking at open issues and unmerged PRs, seems that this project is more or less abandoned. There's little possibility that documentation PR will be merged too :(

**Comment by hoonzis** [comment] 2020-11-05 10:14
Hello, we have juste stumbled on this issue, berore I go into implementation of my own RequestStore from my understanding by default the RequestStateSessionStore is used, so this implementation is not working?

Why does this happen sporadically? All the messages that I receive have **InResponseTo**, only some of them fail the validation, how is this possible if the same storing mechanism (RequestStateSessionStore) is used?

I am thinking maybe for this particular user the PHP session cookie is removed from the browser when getting back from the IdP to login_check, but ofcourse I have no way to check and log the session id before and after getting back from the IdP

**Comment by NullIsNot0** [comment] 2020-11-05 11:44
I store requests in DB, using Doctrine. Symfony 4.4:
```php
<?php
// src/Store/RequestStore.php
namespace App\Store;

use App\Entity\SAMLRequestEntry as RequestEntry;
use Doctrine\ORM\EntityManagerInterface;

use LightSaml\State\Request\RequestState;
use LightSaml\Store\Request\RequestStateStoreInterface;

class RequestStore implements RequestStateStoreInterface
{

    /** @var ObjectManager */
    private $manager;

    /**
     * @param EntityManagerInterface $manager
     */
    public function __construct(EntityManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    /**
     * @param RequestState $state
     *
     * @return RequestStateStoreInterface
     */
    public function set(RequestState $state)
    {
        $requestEntry = $this->manager->find(RequestEntry::class, ['id' => $state->getId()]);
        if (null == $requestEntry) {
            $requestEntry = new RequestEntry();
        }
        $requestEntry->setId($state->getId())
            ->setState(serialize($state));
        $this->manager->persist($requestEntry);
        $this->manager->flush();

        return $this;
    }

    /**
     * @param string $id
     *
     * @return RequestState|null
     */
    public function get($id)
    {
        $requestEntry = $this->manager->find(RequestEntry::class, ['id' => $id]);
        if (null != $requestEntry) {
            return unserialize($requestEntry->getState());
        }

        return null;
    }

    /**
     * @param string $id
     *
     * @return bool
     */
    public function remove($id)
    {
        $requestEntry = $this->manager->find(RequestEntry::class, ['id' => $id]);
        if (null == $requestEntry) {
            return false;
        }

        $this->manager->remove($requestEntry);
        $this->manager->flush();

        return true;
    }

    public function clear()
    {
        //$this->setArray(array());
    }

}
```

```php
<?php
// src/Entity/SAMLRequestEntry.php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="saml_request_entry")
 * @ORM\Entity(repositoryClass="App\Repository\SAMLRequestEntryRepository")
 */
class SAMLRequestEntry
{
    /**
     * @var string
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $state;


    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId($id): self
    {
        $this->id = $id;

        return $this;
    }


    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }
}
```

```yaml
# config/services.yaml
saml_request:
        class: App\Store\RequestStore
        arguments: ["@doctrine.orm.entity_manager"]
```

```yaml
# config/packages/light_saml_symfony_bridge.yaml
light_saml_symfony_bridge:
    own:
        entity_id: "%auth_module_entity_id%"
        credentials:
            -
                certificate: "%auth_module_cert_path%"
                key:         "%auth_module_key_path%"
                password:    ~
    party:
        idp:
            files:
                - "%auth_module_xml_path%"
    store:
        id_state: saml_id_store
        request: saml_request
```

Sorry for the mess in my code, I have not got enough time to make it look nice, but for now it works for me

**Comment by hoonzis** [comment] 2020-11-10 09:09
Thanks @NullIsNot0 I will switch to database storage as well for RequestState. 

I was just wondering what was wrong with the **RequestStateSessionStore** which is part of LightSAML. I can confirm that when I have removed the user sessions manually from the server the problem went away, but I did not investigate further.

**Comment by NullIsNot0** [comment] 2020-11-10 18:30
I went against good programming patterns and didn't investigate what's wrong with existing code and implemented **RequestStore** myself (with the help of reading other github users comments). For now this solution in current project works for me.

**Comment by tim-breitenstein-it** [comment] 2021-01-29 09:20
I have a similar Problem.

Sometimes, about 50%, the POST redirect from the IDP successfully login contains an empty Cookie. So the ACS creates a new Session with a new Session ID and cant find the old Session to verify the SSO login.

**Comment by rvdbogerd** [comment] 2021-03-19 06:50
> Hello, we have juste stumbled on this issue, berore I go into implementation of my own RequestStore from my understanding by default the RequestStateSessionStore is used, so this implementation is not working?
> 
> Why does this happen sporadically? All the messages that I receive have **InResponseTo**, only some of them fail the validation, how is this possible if the same storing mechanism (RequestStateSessionStore) is used?
> 
> I am thinking maybe for this particular user the PHP session cookie is removed from the browser when getting back from the IdP to login_check, but ofcourse I have no way to check and log the session id before and after getting back from the IdP

Correct, I have seen this happening in two cases:
- when the company network security policy is filtering out the cookie
- when you set the same site cookie to "strict" (or "lax"). Try setting it to "none"

This is by design, see https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/

Of course, setting the same site cookie to none is undesired, so please try to implement the RequestStore, so that you have persistent tokens. See examples above.

**Comment by kuldeeppatel68** [comment] 2021-12-02 11:51
> I store requests in DB, using Doctrine. Symfony 4.4:
> 
> ```
> <?php
> // src/Store/RequestStore.php
> namespace App\Store;
> 
> use App\Entity\SAMLRequestEntry as RequestEntry;
> use Doctrine\ORM\EntityManagerInterface;
> 
> use LightSaml\State\Request\RequestState;
> use LightSaml\Store\Request\RequestStateStoreInterface;
> 
> class RequestStore implements RequestStateStoreInterface
> {
> 
>     /** @var ObjectManager */
>     private $manager;
> 
>     /**
>      * @param EntityManagerInterface $manager
>      */
>     public function __construct(EntityManagerInterface $manager)
>     {
>         $this->manager = $manager;
>     }
> 
>     /**
>      * @param RequestState $state
>      *
>      * @return RequestStateStoreInterface
>      */
>     public function set(RequestState $state)
>     {
>         $requestEntry = $this->manager->find(RequestEntry::class, ['id' => $state->getId()]);
>         if (null == $requestEntry) {
>             $requestEntry = new RequestEntry();
>         }
>         $requestEntry->setId($state->getId())
>             ->setState(serialize($state));
>         $this->manager->persist($requestEntry);
>         $this->manager->flush();
> 
>         return $this;
>     }
> 
>     /**
>      * @param string $id
>      *
>      * @return RequestState|null
>      */
>     public function get($id)
>     {
>         $requestEntry = $this->manager->find(RequestEntry::class, ['id' => $id]);
>         if (null != $requestEntry) {
>             return unserialize($requestEntry->getState());
>         }
> 
>         return null;
>     }
> 
>     /**
>      * @param string $id
>      *
>      * @return bool
>      */
>     public function remove($id)
>     {
>         $requestEntry = $this->manager->find(RequestEntry::class, ['id' => $id]);
>         if (null == $requestEntry) {
>             return false;
>         }
> 
>         $this->manager->remove($requestEntry);
>         $this->manager->flush();
> 
>         return true;
>     }
> 
>     public function clear()
>     {
>         //$this->setArray(array());
>     }
> 
> }
> ```
> 
> ```
> <?php
> // src/Entity/SAMLRequestEntry.php
> namespace App\Entity;
> 
> use Doctrine\ORM\Mapping as ORM;
> 
> /**
>  * @ORM\Table(name="saml_request_entry")
>  * @ORM\Entity(repositoryClass="App\Repository\SAMLRequestEntryRepository")
>  */
> class SAMLRequestEntry
> {
>     /**
>      * @var string
>      * @ORM\Id
>      * @ORM\GeneratedValue(strategy="NONE")
>      * @ORM\Column(type="string", length=255, nullable=false)
>      */
>     protected $id;
> 
>     /**
>      * @ORM\Column(type="text", nullable=true)
>      */
>     protected $state;
> 
> 
>     public function getId(): ?string
>     {
>         return $this->id;
>     }
> 
>     public function setId($id): self
>     {
>         $this->id = $id;
> 
>         return $this;
>     }
> 
> 
>     public function getState(): ?string
>     {
>         return $this->state;
>     }
> 
>     public function setState(?string $state): self
>     {
>         $this->state = $state;
> 
>         return $this;
>     }
> }
> ```
> 
> ```yaml
> # config/services.yaml
> saml_request:
>         class: App\Store\RequestStore
>         arguments: ["@doctrine.orm.entity_manager"]
> ```
> 
> ```yaml
> # config/packages/light_saml_symfony_bridge.yaml
> light_saml_symfony_bridge:
>     own:
>         entity_id: "%auth_module_entity_id%"
>         credentials:
>             -
>                 certificate: "%auth_module_cert_path%"
>                 key:         "%auth_module_key_path%"
>                 password:    ~
>     party:
>         idp:
>             files:
>                 - "%auth_module_xml_path%"
>     store:
>         id_state: saml_id_store
>         request: saml_request
> ```
> 
> Sorry for the mess in my code, I have not got enough time to make it look nice, but for now it works for me

Hi @NullIsNot0 , I have made all the required changes but still I have issues while authentication to other sites which I have added in IDP's. 

Can you please share me your source code so I can match with my existing code and fix the issues.

Thanks in advance!

**Closed as completed** 2022-02-10 15:23 UTC
