### ISSUE TITLE
Self-validation of signed AuthnRequest fails

### ISSUE THREAD

**Issue by benreic** [lightSAML/lightSAML#11] opened 2015-12-10 19:07 UTC
This is a follow up to my issue I described at the end of #48 in the `aerialship/lightsaml` repo, (sorry for going off topic there).

I have attached three files to this ticket: 
- my SP metadata
- a working authn request that was generated with the `aerialship/lightsaml` library
- non-working authn request that was generated with the `lightsaml/lightsaml` library

I've removed references to my domain and my salesforce.com domain as I do not want them public. 

I can correctly self validate the "working" xml file in the approach you described in the other ticket, by serializing/deserializing the AuthnRequest object and validating it against my public key. Using the "broken" xml file, I get a `Exception: Reference validation failed` exception.

If you want to take a look at this issue, that would be great. I'm also exploring adding support for `SessionNotOnOrAfter` in the `aerialship/lightsaml` library. I may fork and submit a pull request if I get that working, since the signing works using that library.

[authn-request-broken.txt](https://github.com/lightSAML/lightSAML/files/58595/authn-request-broken.txt)
[authn-request-working.txt](https://github.com/lightSAML/lightSAML/files/58593/authn-request-working.txt)
[gh-sp-metadata.txt](https://github.com/lightSAML/lightSAML/files/58594/gh-sp-metadata.txt)

**Comment by benreic** [comment] 2015-12-10 19:15
As a follow up test, I tried generating an AuthnRequest object using the `aerialship/lightsaml` library and then validating that request using the `lightsaml/lightsaml` library and that also worked. 

This makes me think there is either a bug in the signing process of the `lightsaml/lightsaml` library, or I am constructing my AuthnRequest wrong in my use of the `lightsaml/lightsaml` library,

**Comment by tmilos** [comment] 2015-12-11 08:05
Ref aerialship/lightsaml#48

**Comment by tmilos** [comment] 2015-12-11 09:08
Confirmed. Bug is when root node is signed, like `AuthnRequest` and `Response`, since signature is not added at the end of serialization, but in the middle, so some XML elements are added after the signature is created. Seems, this does not affect signing of inner elements like `Assertion`. 

@benreic , thanks for the report, will be fixed right away.

**Comment by tmilos** [comment] 2015-12-11 09:58
@benreic think it's fixed, and new version 1.0.1 released. Can you please confirm it's working for you?

**Comment by benreic** [comment] 2015-12-11 17:07
Yes, the signing is now working with salesforce, thank you so much for the quick turnaround, I appreciate it.

**Comment by tmilos** [comment] 2015-12-15 07:21
Thanks, glad to hear it works.

**Closed as completed by tmilos** 2015-12-15 07:21 UTC
Labels: bug
